ttsx_two/carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^update_cart_data/$', views.update_cart_data, name='update_cart_data'),
]

ttsx_two/goods/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^detail/$', views.detail, name='detail'),
    url(r'^list/(\d+)/(\d+)/$', views.list, name='list'),
]

ttsx_two/ttsx_two/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^users/', include('users.urls', namespace='users')),
    # favicon.ico图标
    url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico')),
    # url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico')),
]

ttsx_two/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^check_usermail/$', views.check_usermail, name='check_usermail'),

    url(r'^login/$', views.login, name='login'),
    url(r'^login_handle/$', views.login_handle, name='login_handle'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^centerinfo/$', views.centerinfo, name='centerinfo'),
    url(r'^recv_message_handle/$', views.recv_message_handle, name='recv_message_handle'),

    url(r'^centerorder/$', views.centerorder, name='centerorder'),
    url(r'^centersite/$', views.centersite, name='centersite'),

]

ttsx_two/goods/models.py
from django.db import models
from db.base_model import *
from tinymce.models import HTMLField


# 分类模型
class Category(BaseModel):

    # 产品分类名称
    cag_name = models.CharField(max_length=30)


# 商品信息管理类
class GoodsManager(models.Manager):
    pass


# 商品模型
class Goods(BaseModel):

    # 商品名称
    goods_name = models.CharField(max_length=30)
    # 商品价格
    goods_price = models.DecimalField(max_digits=10, decimal_places=2)
    # 商品的图片
    goods_image = models.ImageField()
    # 商品简述
    goods_short = models.CharField(max_length=100)
    # 商品详情
    goods_desc = HTMLField()
    # 商品上架
    goods_status = models.BooleanField(default=True)
    # 商品单位
    goods_unit = models.CharField(max_length=10)
    # 商品访问量
    goods_visit = models.IntegerField(default=0)
    # 商品销量
    goods_sales = models.IntegerField(default=0)
    # 商品分类
    goods_cag = models.ForeignKey(Category)

    objects = GoodsManager()


class Advertise(BaseModel):

    # 广告名称
    ad_name = models.CharField(max_length=30)
    # 广告图片
    ad_image = models.ImageField(upload_to='ad')
    # 广告链接
    ad_link = models.CharField(max_length=100)


# 详细商品页面, 浏览记录
class RecordBrowse(BaseModel):

    # 关联到goods应用下的Goods类
    browse_goods = models.ForeignKey('Goods')
    browse_user = models.ForeignKey('users.User')

ttsx_two/users/models.py
from django.db import models
from db.base_model import *


# 用户管理器
class UserManager(models.Manager):

    def user_by_name(self, username):
        try:
            return self.get(user_name=username)
        except User.DoesNotExist:
            return None


# # 基类创建
# class BaseModel(models.Model):
#
#     # 数据创建时间
#     create_time = models.DateTimeField(auto_now_add=True)
#     # 数据更新时间
#     update_time = models.DateTimeField(auto_now=True)
#     # 是否删除
#     is_delete = models.BooleanField(default=False)
#
#     # 抽象基类, 固定写法
#     class Meta:
#         abstract = True


# 建立用户模型
class User(BaseModel):

    # 用户名
    user_name = models.CharField(max_length=20)
    # 用户密码
    user_pass = models.CharField(max_length=64)
    # 用户联系电话
    user_tele = models.CharField(max_length=11)
    # 用户地址
    user_addr = models.CharField(max_length=100)
    # 用户邮箱
    user_mail = models.CharField(max_length=50)
    # 邮政编码
    user_code = models.CharField(max_length=10)
    # 收件人
    user_recv = models.CharField(max_length=20, default='')

    # 创建自定义管理器
    objects = UserManager()

ttsx_two/users/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from .models import *
import re
import hashlib
from django.http import JsonResponse


# 用户注册页面
def register(request):

    return render(request, 'users/register.html', locals())


# 处理注册
def register_handle(request):

    user_name_input = request.POST.get('user_name', '').strip()
    user_pass1 = request.POST.get('user_pass1', '').strip()
    user_pass2 = request.POST.get('user_pass2', '').strip()
    user_mail_input = request.POST.get('user_mail', '').strip()
    mess = {}
    # 定义函数判断输入是否合法
    def check_register():

        flag = True

        if (not(5<=len(user_name_input)<=20)):
            mess['user_name'] = '请检查用户名长度,保证在5-20个字符之间!'
            flag = False
            return flag

        # 检验用户名是否已经注册过了
        try:
            User.objects.get(user_name=user_name_input)
            mess['user_name'] = '用户名已注册,请重新输入!'
            flag = False
            return flag
        except User.DoesNotExist:
            pass

        if (not(8<=len(user_pass1)<=20)):
            mess['user_pass1'] = '请检查密码长度,保证在8-20个字符之间!'
            flag = False
            return flag
        if (user_pass1 != user_pass2):
            mess['user_pass2'] = '两次输入的密码不相同,请重新输入!'
            flag = False
            return flag

        reg = '^[a-z0-9][\w\.\-]*@[a-z0-9]+(\.[a-z]{2,5}){1,2}$'
        if not re.match(reg, user_mail_input):
            mess['user_mail'] = '您输入的邮箱不存在!'
            flag = False
            return flag

        # 检验邮箱是否已经注册过了
        try:
            users = User.objects.get(user_mail=user_mail_input)
            mess['user_mail'] = '邮箱已注册,请重新输入!'
            flag = False
            return flag
        except User.DoesNotExist:
            pass
        return flag

    # 判断输入是否合法
    if check_register():
        # 1.1 输入合法,保存到数据库
        user = User()
        user.user_name = user_name_input

        # 密码需要加密后再存储到数据库
        sha = hashlib.sha256()
        # 前后加符号后再加密,
        pass_word = 'djkfjddk' + user_pass1 + 'jfkdjfdk'
        sha.update(pass_word.encode('utf-8'))
        user.user_pass = sha.hexdigest()

        user.user_mail = user_mail_input
        user.save()
        return render(request, 'users/login.html', locals())
    else:
        # 1.2 不合法,跳转到注册页面
        return render(request, 'users/register.html', locals())


# 注册时, ajax 检测用户名是否存在
def check_username(request):

    # 从register.js中获得参数
    user_name_input2 = request.GET.get('username', '').strip()
    print(user_name_input2, 'aaaaaaaaaaaaaaaaaaaa')

    if User.objects.get(user_name=user_name_input2):
        return JsonResponse({'ret': 1})
    else:
        return JsonResponse({'ret': 0})


# 注册时, ajax 检测用户邮箱是否存在
def check_usermail(request):

    # 从register.js中获得参数
    user_mail_input2 = request.GET.get('usermail', '').strip()
    print(user_mail_input2, 'bbbbbbbbbbbbbbbbbbbbb')

    if User.objects.get(user_mail=user_mail_input2):
        return JsonResponse({'ret': 1})
    else:
        return JsonResponse({'ret': 0})


# 用户登录
def login(request):

    return render(request, 'users/login.html', locals())


# 处理登录
def login_handle(request):

    user_name_login = request.POST.get('username', '').strip()
    user_pwd_login = request.POST.get('pwd', '').strip()

    user = User.objects.user_by_name(user_name_login)

    # 检测登录参数
    def check_login_params():

        flag = True
        if (not(5<=len(user_name_login)<=20)):
            flag = False
            return flag

        if (not(8<=len(user_pwd_login)<=20)):
            flag = False
            return flag

        if user:
            # 密码需要加密后再存储到数据库
            sha = hashlib.sha256()
            # 前后加符号后再加密,
            pass_word2 = 'djkfjddk' + user_pwd_login + 'jfkdjfdk'
            sha.update(pass_word2.encode('utf-8'))
            pass_word2 = sha.hexdigest()

            if pass_word2 == user.user_pass:
                return flag
            else:
                flag = False
                return flag
        else:
            flag = False
            return flag

        return flag

    if check_login_params():

        # 1.记录用户状态
        request.session['username'] = user_name_login
        request.session['uid'] = user.id

        # 2.是否需要记录用户名, 设置cookie
        remember = request.POST.get('user_memb', '').strip()

        if remember:
            HttpResponse.set_cookie('username', user_name_login, max_age=60*60*24)

        # 3.获得跳转 url
        url = request.COOKIES.get('pre_url', '')
        if not url:
            url = reverse('goods:index')
        return redirect(url)

    else:
        return render(request, 'users/login.html')


# 退出登录
def logout(request):

    # 1.保存最近一次 url
    url = request.COOKIES.get('pre_url', '').strip()
    if not url:
        url = reverse('goods:index')

    # 2.清空session
    request.session.flush()

    return redirect(url)


# 装饰器,检查用户是否登录
def view_premission(func):
    def wrapper(request, *args, **kwargs):
        
        if request.session.get('username', ''):
            return func(request, *args, **kwargs)
        else:
            return redirect(reverse('users:login'))
    return wrapper


# 用户中心
@view_premission
def centerinfo(request):

    user = User.objects.get(user_name=request.session.get('username', ''))

    return render(request, 'users/user_center_info.html', locals())


# 处理收件人信息
def recv_message_handle(request):

    user_recv = request.POST.get('user_recv', '')
    user_addr = request.POST.get('user_addr', '')
    user_code = request.POST.get('user_code', '')
    user_tele = request.POST.get('user_tele', '')

    if len(user_recv) != 0 and len(user_addr) != 0 and len(user_code) == 6 and len(user_tele) == 11:
        user = User.objects.get(user_name=request.session.get('username', ''))
        user.user_recv = user_recv
        user.user_addr = user_addr
        user.user_code = user_code
        user.user_tele = user_tele
        user.save()

    return redirect(reverse('users:centersite'))


# 用户订单
@view_premission
def centerorder(request):

    return render(request, 'users/user_center_order.html', locals())


# 用户地址
@view_premission
def centersite(request):

    user = User.objects.get(user_name=request.session.get('username', ''))
    return render(request, 'users/user_center_site.html', locals())

ttsx_two/templates/users/login.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}



{% block body %}


	<div class="login_top clearfix">
		<a href="../goods/index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">

					<form method="post" action="{% url 'users:login_handle' %}">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>

						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="user_memb">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>

				</div>
			</div>
		</div>
	</div>
{% endblock body %}

{% block footer_css %}no-mp{% endblock %}



ttsx_two/templates/users/register.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}


{% block header_js %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock header_js %}


{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'users:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">

				<form method="post" action="{% url 'users:register_handle' %}">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
                        <span class="error_tip_info">{{ mess.user_name }}</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="user_pass1" id="pwd">
						<span class="error_tip">提示信息</span>
                        <span class="error_tip_info">{{ mess.user_pass1 }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="user_pass2" id="cpwd">
						<span class="error_tip">提示信息</span>
                        <span class="error_tip_info">{{ mess.user_pass2 }}</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="user_mail" id="email">
						<span class="error_tip">提示信息</span>
                        <span class="error_tip_info">{{ mess.user_mail }}</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="user_allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>

			</div>

		</div>

	</div>


{% endblock body %}


{% block footer_css %}no-mp{% endblock footer_css %}


ttsx_two/templates/users/user_center_info.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}

{# 加载过滤器 #}
{% load users_filters %}

{% block body %}

    {# 是否登录的状态 #}
    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">

        {# 用户中心左侧区域 #}
        {% include 'users/user_left_area.html' with flag='info' %}

		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>收件人：</span>{{ user.user_recv|default:'未填写' }}</li>
							<li><span>联系方式：</span>{{ user.user_tele|default:'未填写' }}</li>
							<li><span>联系地址：</span>{{ user.user_addr|default:'未填写' }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

                {% for record in user.recordbrowse_set.all|record_sort %}
				<li>
					<a href="{% url 'goods:detail' %}?id={{ record.browse_goods.id }}"><img src="{% static record.browse_goods.goods_image %}"></a>
					<h4><a href="{% url 'goods:detail' %}?id={{ record.browse_goods.id }}">{{ record.browse_goods.goods_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ record.browse_goods.goods_price }}</span>
						<span class="unit">{{ record.browse_goods.goods_price }}/{{ record.browse_goods.goods_unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}

			</ul>
		</div>
		</div>
	</div>

{% endblock body %}

ttsx_two/templates/users/user_center_order.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}


{% block body %}

    {# 是否登录的状态 #}
    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="../goods/index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">

		{# 用户中心左侧区域 #}
        {% include 'users/user_left_area.html' with flag='order' %}

		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>

{% endblock body %}

ttsx_two/templates/users/user_center_site.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}


{% block body %}

    {# 是否登录的状态 #}
    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="../goods/index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">

		{# 用户中心左侧区域 #}
        {% include 'users/user_left_area.html' with flag='site' %}

		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.user_addr|default:'未填写' }} （{{ user.user_recv|default:'未填写' }} 收） {{ user.user_tele|default:'未填写' }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">

					<form action="{% url 'users:recv_message_handle' %}" method="post">
                        {% csrf_token %}

						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="user_recv" value="{{ user.user_recv }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="user_addr">{{ user.user_addr }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="user_code" value="{{ user.user_code }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="user_tele" value="{{ user.user_tele }}">
						</div>

						<input type="submit" value="提交" class="info_submit">
					</form>

				</div>
		</div>
	</div>

{% endblock %}

ttsx_two/templates/users/user_left_area.html
{% load users_filters %}


<div class="left_menu_con clearfix">
    <h3>用户中心</h3>
    <ul>

    {# abc|filer_name #}
    {# flag|create_menu #}

    {% with menus=flag|create_menu  %}
        {% for menu in menus %}
        <li><a href="{{ menu.link }}" class="{{ menu.active }}"  >· {{ menu.name }}</a></li>
        {% endfor %}
    {% endwith %}

    </ul>
</div>


{# 方法2 #}
{#<div class="left_menu_con clearfix">#}
{#    <h3>用户中心</h3>#}
{#    <ul>#}
{#        <li><a href="{% url 'users:centerinfo' %}" {% if flag == 'info' %}#}
{#        class="active"#}
{#        {% endif %} >· 个人信息</a></li>#}
{#        <li><a href="{% url 'users:centerorder' %}" {% if flag == 'order' %}#}
{#        class="active"#}
{#        {% endif %}>· 全部订单</a></li>#}
{#        <li><a href="{% url 'users:centersite' %}" {% if flag == 'site' %}#}
{#        class="active"#}
{#        {% endif %} >· 收货地址</a></li>#}
{#    </ul>#}
{#</div>#}