ttsx_two/carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^update_cart_data/$', views.update_cart_data, name='update_cart_data'),
]

ttsx_two/ttsx_two/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^users/', include('users.urls', namespace='users')),
    # favicon.ico图标
    url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico')),
    # url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico')),
]

ttsx_two/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^check_usermail/$', views.check_usermail, name='check_usermail'),

    url(r'^login/$', views.login, name='login'),
    url(r'^login_handle/$', views.login_handle, name='login_handle'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^centerinfo/$', views.centerinfo, name='centerinfo'),
    url(r'^recv_message_handle/$', views.recv_message_handle, name='recv_message_handle'),

    url(r'^centerorder/$', views.centerorder, name='centerorder'),
    url(r'^centersite/$', views.centersite, name='centersite'),

]

ttsx_two/carts/models.py
from django.db import models
from db.base_model import BaseModel


# 购物车管理模型
class CartManager(models.Manager):
    pass


# 购物车模型
class Cart(BaseModel):
    cart_goods = models.ForeignKey('goods.Goods')
    cart_user = models.ForeignKey('users.User')
    cart_amount = models.IntegerField()

    objects = CartManager()

ttsx_two/carts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from .models import *


# 我的购物车页面
def index(request):

    carts = Cart.objects.filter(cart_user_id=request.session.get('uid', ''))

    money = 0
    total = 0
    for cart in carts:

        cart.total = cart.cart_goods.goods_price*cart.cart_amount
        money += cart.total
        total += cart.cart_amount

    return render(request, 'carts/cart.html', locals())


# 点击加入购物车时, 数据存储到数据库
def addcart(request):

    goods_id = request.GET.get('goods_id', '').strip()
    goods_num = request.GET.get('goods_num', '').strip()
    user_id = request.session.get('uid', '')

    # 如果存在,则更新数量
    try:
        cart = Cart.objects.get(cart_user_id=user_id, cart_goods_id=goods_id)
        cart.cart_amount = cart.cart_amount + int(goods_num)
        cart.save()
        # cart = Cart.objects.get(cart_goods_id=goods_id, cart_user_id=user_id)
        # cart.cart_amount = cart.cart_amount + int(goods_num)
        # cart.save()
    except Cart.DoesNotExist:
        cart = Cart()
        cart.cart_goods_id = goods_id
        cart.cart_amount = goods_num
        cart.cart_user_id = user_id
        cart.save()

    # 更新购物车总数量
    carts = Cart.objects.filter(cart_user_id=user_id)
    total = 0
    for cart in carts:
        total = cart.cart_amount
    return JsonResponse({'total': total})


# 我的购物车中, 修改数量等数据, 数据库联动
def update_cart_data(request):

    goods_id = request.GET.get('goods_id', '')
    goods_num = request.GET.get('goods_num', '')

    try:
        cart = Cart.objects.get(cart_user_id=request.session.get('uid', ''), cart_goods_id=goods_id)
        cart.cart_goods_id = goods_id
        cart.cart_amount = goods_num
        cart.save()
    except Cart.DoesNotExist:
        return JsonResponse({'ret': 0})
    return JsonResponse({'ret': 1})

ttsx_two/templates/carts/cart.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}

{% block header_js %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script >
        $(function () {
            $('.add').click(function () {
                num = $(this).parents('.cart_list_td').find('.num_show').val();
                num = parseInt(num) + 1;
                $(this).parents('.cart_list_td').find('.num_show').val(num);

                update_mysql_data($(this));

            });

            $('.minus').click(function () {
                num = $(this).parents('.cart_list_td').find('.num_show').val();
                num = parseInt(num) - 1
                if(num <= 0) {
                    num = 1
                }
                $(this).parents('.cart_list_td').find('.num_show').val(num);

                update_mysql_data($(this))

            });

            {# 更新后端数据 #}
            function update_mysql_data(obj) {

                goods_id = obj.parents('.cart_list_td').find('input:checkbox').val();
                goods_num = obj.parents('.cart_list_td').find('.num_show').val();

                $.get('{% url 'carts:update_cart_data' %}', {'goods_id': goods_id, 'goods_num': goods_num}, function (data) {

                    {# 确定mysql已更新, 前端页面动态更新 #}
                    if (data.ret == 1){

                        {#  1.更新单品价格  #}
                        price = parseFloat(obj.parents('.cart_list_td').find('.col05').html());
                        cart_money = price*goods_num;
                        obj.parents('.cart_list_td').find('.col07').html(cart_money.toFixed(2) + '元')

                        total_money = 0
                        total_num = 0
                        {#  1.更新总价格和总数量  #}
                        $('.cart_list_td').each(function () {

                            if (!$(this).find('input:checkbox').prop('checked')){
                                return true;
                            };

                            cart_money = parseFloat($(this).find('.col07').html());
                            goods_num = $(this).find('.num_show').val();

                            total_money += cart_money;
                            total_num += parseInt(goods_num);

                        });

                        $('.settlements .col03').find('em').html(total_money.toFixed(2) + '元');
                        $('.settlements .col03').find('b').html(total_num);

                    }
                });

            };



        })

    </script>

{% endblock header_js %}

{% block body %}

    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="../goods/index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>


    <form method="post" action="{% url 'users:centerorder' %}">
    {% csrf_token %}
    {% for cart in carts %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" value="{{ cart.cart_goods.id }}" checked></li>
		<li class="col02"><img src="{% static cart.cart_goods.goods_image %}"></li>
		<li class="col03">{{ cart.cart_goods.goods_name }}<br><em>{{ cart.cart_goods.goods_price }}元/{{ cart.cart_goods.goods_unit }}</em></li>
		<li class="col04">{{ cart.cart_goods.goods_unit }}</li>
		<li class="col05">{{ cart.cart_goods.goods_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ cart.cart_amount }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ cart.total }}</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}
    </form>

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ money }}</em><br>共计<b>{{ total }}</b>件商品</li>
		<li class="col04"><a href="../order/place_order.html">去结算</a></li>
	</ul>

{% endblock body %}