ttsx_two/carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^update_cart_data/$', views.update_cart_data, name='update_cart_data'),
]

ttsx_two/goods/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^detail/$', views.detail, name='detail'),
    url(r'^list/(\d+)/(\d+)/$', views.list, name='list'),
]

ttsx_two/ttsx_two/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^users/', include('users.urls', namespace='users')),
    # favicon.ico图标
    url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico')),
    # url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico')),
]

ttsx_two/goods/models.py
from django.db import models
from db.base_model import *
from tinymce.models import HTMLField


# 分类模型
class Category(BaseModel):

    # 产品分类名称
    cag_name = models.CharField(max_length=30)


# 商品信息管理类
class GoodsManager(models.Manager):
    pass


# 商品模型
class Goods(BaseModel):

    # 商品名称
    goods_name = models.CharField(max_length=30)
    # 商品价格
    goods_price = models.DecimalField(max_digits=10, decimal_places=2)
    # 商品的图片
    goods_image = models.ImageField()
    # 商品简述
    goods_short = models.CharField(max_length=100)
    # 商品详情
    goods_desc = HTMLField()
    # 商品上架
    goods_status = models.BooleanField(default=True)
    # 商品单位
    goods_unit = models.CharField(max_length=10)
    # 商品访问量
    goods_visit = models.IntegerField(default=0)
    # 商品销量
    goods_sales = models.IntegerField(default=0)
    # 商品分类
    goods_cag = models.ForeignKey(Category)

    objects = GoodsManager()


class Advertise(BaseModel):

    # 广告名称
    ad_name = models.CharField(max_length=30)
    # 广告图片
    ad_image = models.ImageField(upload_to='ad')
    # 广告链接
    ad_link = models.CharField(max_length=100)


# 详细商品页面, 浏览记录
class RecordBrowse(BaseModel):

    # 关联到goods应用下的Goods类
    browse_goods = models.ForeignKey('Goods')
    browse_user = models.ForeignKey('users.User')

ttsx_two/goods/views.py
from django.shortcuts import render
from .models import *
from .functions import *
from django.core.paginator import Paginator
from carts.models import Cart


# 三个页面要显示当前购物车数量,用装饰器完成
def cart_total_amount(func):
    def inner(request, *args, **kwargs):
        carts = Cart.objects.filter(cart_user_id=request.session.get('uid', ''))

        total = 0
        for cart in carts:
            total += cart.cart_amount
        request.total = total

        return func(request, *args, **kwargs)
    return inner


# 商品主页
@cart_total_amount
def index(request):

    ad1 = Advertise.objects.all()[:4]
    ad2 = Advertise.objects.all()[4:]

    # 获得商品所有分类
    cags = Category.objects.all()

    for cag in cags:

        # 4种最新的商品
        cag.new = Goods.objects.filter(goods_cag=cag).order_by('-id')[:4]
        # 3种热销商品
        cag.hot = Goods.objects.filter(goods_cag=cag).order_by('goods_sales')[:3]

    return render(request, 'goods/index.html', locals())


# 商品详细页
@cart_total_amount
def detail(request):

    # 根据跳转url中的id,得到商品
    g_id = request.GET.get('id', '').strip()
    # goods = Goods.objects.get(id=g_id)
    goods = Goods.objects.get(pk=g_id)

    # 获取最新的2个商品
    goods_new = Goods.objects.all().order_by('-id')[:2]

    # 更新用户浏览记录
    update_user_browse(request)

    return render(request, 'goods/detail.html', locals())


# 商品列表页
@cart_total_amount
def list(request, cag_id, page_id):

    # 获得商品分类
    cags = Category.objects.all()

    # 从url中获得参数show
    show = request.GET.get('show', '')

    # 根据分类获得商品列表
    if show == '':
        goods_list = Goods.objects.filter(goods_cag_id=cag_id)
    if show == 'price':
        goods_list = Goods.objects.filter(goods_cag_id=cag_id).order_by('-goods_price')
    if show == 'hot':
        goods_list = Goods.objects.filter(goods_cag_id=cag_id).order_by('-goods_price')

    # 创建分页对象
    paginator = Paginator(goods_list, 10)

    current_page = paginator.page(page_id)

    # 获取最新的2个商品
    goods_new = Goods.objects.all().order_by('-id')[:2]

    return render(request, 'goods/list.html', locals())

ttsx_two/templates/goods/detail.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}

{% block header_js %}
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $(function () {
            $('.add').click(function () {
                num = $('.num_show').val()
                num = parseInt(num) + 1

                update_price(num)

            });

            $('.minus').click(function () {
                num = $('.num_show').val()
                num = parseInt(num) - 1
                if(num <= 0) {
                    num = 1
                }
                update_price(num)

            });

            function update_price(num) {
                $('.num_show').val(num)

                price = $('.show_pirze').find('em').html()
                total = num*parseFloat(price)
                $('.total').find('em').html(total+'元')
            };

            {# 加入购物车,ajax传参#}
            $('.add_cart').click(function () {
                goods_num = $('.num_show').val()
                goods_id = $('.goods_id').val()
                $.get('{% url "carts:addcart" %}', {'goods_num':goods_num, 'goods_id':goods_id},
                function (data) {
                    alert('加入购物车成功!')
                    $('#show_count').html(data.total)
                }
                );
            });
        })

    </script>

{% endblock header_js %}


{% block body %}

    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>

        {# 我的购物车 #}
        {% include 'goods/mycart.html' %}

	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="{% url 'goods:list' 1 1 %}" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goods:list' 2 1 %}" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goods:list' 3 1 %}" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goods:list' 4 1 %}" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goods:list' 5 1 %}" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goods:list' 6 1 %}" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{% static goods.goods_image %}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.goods_name }}</h3>
			<p>{{ goods.goods_short }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.goods_price }}</em></span>
				<span class="show_unit">单  位：{{ goods.goods_unit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div>
			</div>
			<div class="total">总价：<em>{{ goods.goods_price }}元</em></div>
            <div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
                <input type="hidden" class="goods_id" value="{{ goods.id }}">
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for good in goods_new %}
					<li>
						<a href="{% url 'goods:detail' %}?id={{ good.id }} "><img src="{% static good.goods_image %}"></a>
						<h4><a href="{% url 'goods:detail' %}?id={{ good.id }}">{{ good.goods_name }}</a></h4>
						<div class="prize">￥{{ good.goods_price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_desc }}</dd>
				</dl>
			</div>

		</div>
	</div>

{% endblock body %}


{% block footer_js %}

	<div class="add_jump"></div>

	<script type="text/javascript" src="{% static 'js/jquery-1.12.2.js' %}"></script>
	<script type="text/javascript">
{#		var $add_x = $('#add_cart').offset().top;#}
{#		var $add_y = $('#add_cart').offset().left;#}
{##}
{#		var $to_x = $('#show_count').offset().top;#}
{#		var $to_y = $('#show_count').offset().left;#}
{##}
{#		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})#}
{#		$('#add_cart').click(function(){#}
{#			$(".add_jump").stop().animate({#}
{#				'left': $to_y+7,#}
{#				'top': $to_x+7},#}
{#				"fast", function() {#}
{#					$(".add_jump").fadeOut('fast',function(){#}
{#						$('#show_count').html(2);#}
{#					});#}
{#			});#}
{#		})#}
	</script>
{% endblock footer_js %}

ttsx_two/templates/goods/index.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}

{# 加载过滤器 #}
{% load goods_filters %}

{% block header_js %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock header_js %}


{# 首页主体部分内容 #}
{% block body %}

	{# 是否登录的状态 #}
    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="#" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>

        {# 我的购物车 #}
        {% include 'goods/mycart.html' %}

	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="{% url 'goods:list' 1 1 %}" class="fruit">新鲜水果</a></li>
			<li><a href="{% url 'goods:list' 2 1 %}" class="seafood">海鲜水产</a></li>
			<li><a href="{% url 'goods:list' 3 1 %}" class="meet">猪牛羊肉</a></li>
			<li><a href="{% url 'goods:list' 4 1 %}" class="egg">禽类蛋品</a></li>
			<li><a href="{% url 'goods:list' 5 1 %}" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="{% url 'goods:list' 6 1 %}" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">

			<ul class="slide_pics">

                {% for ad in ad1 %}
				<li ><a href="{{ ad.ad_link }}"><img src="{% static ad.ad_image %}" alt="幻灯片"></a></li>
                {% endfor %}

			</ul>

			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>

		<div class="adv fl">
            {% for ad in ad2 %}
			<a href="http://www.baidu.com"><img src="{% static ad.ad_image %}"></a>
            {% endfor %}
		</div>

	</div>

    {% for cag in cags %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ cag.id }}" >{{ cag.cag_name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for goods in cag.hot %}
				<a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static forloop.counter|cag_image %}"></div>
			<ul class="goods_list fl">

                {% for goods in cag.new %}
				<li>
					<h4><a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a></h4>
					<a href="{% url 'goods:detail' %}?id={{ goods.id }}"><img src="{% static goods.goods_image %}"></a>
					<div class="prize">¥ {{ goods.goods_price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}

{% endblock body %}

ttsx_two/templates/goods/list.html
{# 继承父模板 #}
{% extends 'common/base.html' %}

{# 加载标签 #}
{% load staticfiles %}



{% block body %}

    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>

		{# 我的购物车 #}
        {% include 'goods/mycart.html' %}

	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="{% url 'goods:list' cags.0.id 1 %}" class="fruit">{{ cags.0.cag_name }}</a></li>
					<li><a href="{% url 'goods:list' cags.1.id 1 %}" class="seafood">{{ cags.1.cag_name }}</a></li>
					<li><a href="{% url 'goods:list' cags.2.id 1 %}" class="meet">{{ cags.2.cag_name }}</a></li>
					<li><a href="{% url 'goods:list' cags.3.id 1 %}" class="egg">{{ cags.3.cag_name }}</a></li>
					<li><a href="{% url 'goods:list' cags.4.id 1 %}" class="vegetables">{{ cags.4.cag_name }}</a></li>
					<li><a href="{% url 'goods:list' cags.5.id 1 %}" class="ice">{{ cags.5.cag_name }}</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>

                    {% for goods in goods_new %}
					<li>
						<a href="{% url 'goods:detail' %}?id={{ goods.id }}"><img src="{% static goods.goods_image %}"></a>
						<h4><a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a></h4>
						<div class="prize">￥{{ goods.goods_price }}</div>
					</li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' cag_id 1 %}" {% if show == '' %}
				 class="active"
				{% endif %}>默认</a>
				<a href="{% url 'goods:list' cag_id 1 %}?show=price " {% if show == 'price' %}
				 class="active"
				{% endif %}>价格</a>
				<a href="{% url 'goods:list' cag_id 1 %}?show=hot " {% if show == 'hot' %}
				 class="active"
				{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">

                {% for goods in current_page %}
				<li>
					<a href="{% url 'goods:detail' %}?id={{ goods.id }}"><img src="{% static goods.goods_image %}"></a>
					<h4><a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.goods_price }}</span>
						<span class="unit">{{ goods.goods_price }}/{{ goods.goods_unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
				<a href="#">&lt上一页</a>
				<a href="#" class="active">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">5</a>
				<a href="#">下一页&gt</a>
			</div>
		</div>
	</div>

{% endblock body %}

ttsx_two/templates/goods/mycart.html
<div class="guest_cart fr">
    <a href="../carts/cart.html" class="cart_name fl">我的购物车</a>
    <div class="goods_count fl" id="show_count">{{ request.total }}</div>
</div>