ttsx_two/carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^update_cart_data/$', views.update_cart_data, name='update_cart_data'),
]

ttsx_two/ttsx_two/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^users/', include('users.urls', namespace='users')),
    # favicon.ico图标
    url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico')),
    # url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico')),
]

ttsx_two/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^check_usermail/$', views.check_usermail, name='check_usermail'),

    url(r'^login/$', views.login, name='login'),
    url(r'^login_handle/$', views.login_handle, name='login_handle'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^centerinfo/$', views.centerinfo, name='centerinfo'),
    url(r'^recv_message_handle/$', views.recv_message_handle, name='recv_message_handle'),

    url(r'^centerorder/$', views.centerorder, name='centerorder'),
    url(r'^centersite/$', views.centersite, name='centersite'),

]

ttsx_two/templates/common/base.html
{% load staticfiles %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-商品详情</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {# 头部js部分 #}
    {% block header_js %}{% endblock header_js %}

</head>
<body>


{# 网页主体部分内容 #}
{% block body %}{% endblock body %}



	<div class="footer {% block footer_css %}{% endblock %}">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<div class="add_jump"></div>

	{% block footer_js %}{% endblock footer_js %}

</body>
</html>

ttsx_two/templates/common/status.html
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {% if request.session.username %}
				<div class="login_btn fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
                    <a href="{% url 'users:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
                {% endif %}


				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:centerinfo' %}" target="_blank">用户中心</a>
					<span>|</span>
					<a href="{% url 'carts:index' %}" target="_blank">我的购物车</a>
					<span>|</span>
					<a href="{% url 'users:centerorder' %}" target="_blank">我的订单</a>
				</div>


			</div>
		</div>
	</div>